/**
 * tags 配置
 * name: 文件名称
 * desc: 基本描述
 * url: 参考链接
 * class: 分类,通过空格分隔 hmtl5 removed (跟，嵌入，表单等等) 闭合|非闭合closed 块级|内联 blocked
 */
/**
根元素：rootval   1
表单元素： formval   15
表格元素:  tableval  10
元数据脚本：metascriptval  8
嵌入：embedval  12
文本语义：textval 28
分组：groupval  14
文档内容： documentval  15
互动：interactiveval  4
 */
export const tags = [
    [{
        name: 'html',
        desc: '',
        url: '',
        class: 'rootval'
    }, {
        name: '',
        desc: '',
        url: '',
        class: ''
    }, {
        name: '',
        desc: '',
        url: '',
        class: ''
    }, {
        name: '',
        desc: '',
        url: '',
        class: ''
    }, {
        name: '',
        desc: '',
        url: '',
        class: ''
    }, {
        name: '',
        desc: '',
        url: '',
        class: ''
    }, {
        name: '',
        desc: '',
        url: '',
        class: ''
    }, {
        name: '',
        desc: '',
        url: '',
        class: ''
    }, {
        name: '',
        desc: '',
        url: '',
        class: ''
    }, {
        name: '',
        desc: '',
        url: '',
        class: ''
    }, {
        name: '',
        desc: '',
        url: '',
        class: ''
    }, {
        name: '',
        desc: '',
        url: '',
        class: ''
    }, {
        name: '',
        desc: '',
        url: '',
        class: ''
    }, {
        name: '',
        desc: '',
        url: '',
        class: ''
    }, {
        name: '',
        desc: '',
        url: '',
        class: ''
    }, {
        name: '',
        desc: '',
        url: '',
        class: ''
    }, {
        name: '',
        desc: '',
        url: '',
        class: ''
    }, {
        name: 'table',
        desc: '',
        url: '',
        class: 'tableval'
    }],
    [{
        name: 'head',
        desc: '',
        url: '',
        class: 'metaval'
    }, {
        name: 'span',
        desc: '',
        url: '',
        class: 'textval'
    }, {
        name: '',
        desc: '',
        url: '',
        class: ''
    }, {
        name: '',
        desc: '',
        url: '',
        class: ''
    }, {
        name: '',
        desc: '',
        url: '',
        class: ''
    }, {
        name: '',
        desc: '',
        url: '',
        class: ''
    }, {
        name: '',
        desc: '',
        url: '',
        class: ''
    }, {
        name: '',
        desc: '',
        url: '',
        class: ''
    }, {
        name: '',
        desc: '',
        url: '',
        class: ''
    }, {
        name: '',
        desc: '',
        url: '',
        class: ''
    }, {
        name: 'div',
        desc: '',
        url: '',
        class: 'blockval'
    }, {
        name: 'fieldset',
        desc: '',
        url: '',
        class: 'formval'
    }, {
        name: 'form',
        desc: '',
        url: '',
        class: 'formval'
    }, {
        name: 'meter',
        desc: '',
        url: '',
        class: 'formval'
    }, {
        name: 'body',
        desc: '',
        url: '',
        class: 'documentval'
    }, {
        name: 'h1',
        desc: '',
        url: '',
        class: 'documentval'
    }, {
        name: 'col',
        desc: '',
        url: '',
        class: 'tableval'
    }, {
        name: 'thead',
        desc: '',
        url: '',
        class: 'tableval'
    }],
    [{
        name: 'title',
        desc: '',
        url: '',
        class: 'metaval'
    }, {
        name: 'a',
        desc: '',
        url: '',
        class: 'textval'
    }, {
        name: 'em',
        desc: '',
        url: '',
        class: 'textval'
    }, {
        name: 'strong',
        desc: '',
        url: '',
        class: 'textval'
    }, {
        name: 'small',
        desc: '',
        url: '',
        class: 'textval'
    }, {
        name: 'cite',
        desc: '',
        url: '',
        class: 'textval'
    }, {
        name: 's',
        desc: '',
        url: '',
        class: 'textval'
    }, {
        name: 'q',
        desc: '',
        url: '',
        class: 'textval'
    }, {
        name: 'p',
        desc: '',
        url: '',
        class: 'blockval'
    }, {
        name: 'hr',
        desc: '',
        url: '',
        class: 'blockval'
    }, {
        name: 'figcaption',
        desc: '',
        url: '',
        class: 'blockval'
    }, {
        name: 'select',
        desc: '',
        url: '',
        class: 'formval'
    }, {
        name: 'option',
        desc: '',
        url: '',
        class: 'formval'
    }, {
        name: 'legend',
        desc: '',
        url: '',
        class: 'formval'
    }, {
        name: 'section',
        desc: '',
        url: '',
        class: 'documentval'
    }, {
        name: 'h2',
        desc: '',
        url: '',
        class: 'documentval'
    }, {
        name: 'colgroup',
        desc: '',
        url: '',
        class: 'tableval'
    }, {
        name: 'tbody',
        desc: '',
        url: '',
        class: 'tableval'
    }],
    [{
        name: 'meta',
        desc: '',
        url: '',
        class: 'metaval'
    }, {
        name: 'template',
        desc: '',
        url: '',
        class: 'metaval'
    }, {
        name: 'abbr',
        desc: '',
        url: '',
        class: 'textval'
    }, {
        name: 'data',
        desc: '',
        url: '',
        class: 'textval'
    }, {
        name: 'time',
        desc: '',
        url: '',
        class: 'textval'
    }, {
        name: 'code',
        desc: '',
        url: '',
        class: 'textval'
    }, {
        name: 'var',
        desc: '',
        url: '',
        class: 'textval'
    }, {
        name: 'samp',
        desc: '',
        url: '',
        class: 'textval'
    }, {
        name: 'br',
        desc: '',
        url: '',
        class: 'blockval'
    }, {
        name: 'pre',
        desc: '',
        url: '',
        class: 'blockval'
    }, {
        name: 'figure',
        desc: '',
        url: '',
        class: 'blockval'
    }, {
        name: 'label',
        desc: '',
        url: '',
        class: 'formval'
    }, {
        name: 'optgroup',
        desc: '',
        url: '',
        class: 'formval'
    }, {
        name: 'menu',
        desc: '',
        url: '',
        class: 'interactiveval'
    }, {
        name: 'nav',
        desc: '',
        url: '',
        class: 'documentval'
    }, {
        name: 'h3',
        desc: '',
        url: '',
        class: 'documentval'
    }, {
        name: 'caption',
        desc: '',
        url: '',
        class: 'tableval'
    }, {
        name: 'tfoot',
        desc: '',
        url: '',
        class: 'tableval'
    }],
    [{
        name: 'base',
        desc: '',
        url: '',
        class: 'metaval'
    }, {
        name: 'slot',
        desc: '',
        url: '',
        class: 'metaval'
    }, {
        name: 'kbd',
        desc: '',
        url: '',
        class: 'textval'
    }, {
        name: 'sub',
        desc: '',
        url: '',
        class: 'textval'
    }, {
        name: 'sup',
        desc: '',
        url: '',
        class: 'textval'
    }, {
        name: 'i',
        desc: '',
        url: '',
        class: 'textval'
    }, {
        name: 'b',
        desc: '',
        url: '',
        class: 'textval'
    }, {
        name: 'mark',
        desc: '',
        url: '',
        class: 'textval'
    }, {
        name: 'ol',
        desc: '',
        url: '',
        class: 'blockval'
    }, {
        name: 'ul',
        desc: '',
        url: '',
        class: 'blockval'
    }, {
        name: 'li',
        desc: '',
        url: '',
        class: 'blockval'
    }, {
        name: 'input',
        desc: '',
        url: '',
        class: 'formval'
    }, {
        name: 'output',
        desc: '',
        url: '',
        class: 'formval'
    }, {
        name: 'command',
        desc: '',
        url: '',
        class: 'interactiveval'
    }, {
        name: 'main',
        desc: '',
        url: '',
        class: 'documentval'
    }, {
        name: 'h4',
        desc: '',
        url: '',
        class: 'documentval'
    }, {
        name: 'aside',
        desc: '',
        url: '',
        class: 'documentval'
    }, {
        name: 'tr',
        desc: '',
        url: '',
        class: 'tableval'
    }],
    [{
        name: 'link',
        desc: '',
        url: '',
        class: 'metaval'
    }, {
        name: 'noscript',
        desc: '',
        url: '',
        class: 'metaval'
    }, {
        name: 'ruby',
        desc: '',
        url: '',
        class: 'textval'
    }, {
        name: 'rb',
        desc: '',
        url: '',
        class: 'textval'
    }, {
        name: 'rt',
        desc: '',
        url: '',
        class: 'textval'
    }, {
        name: 'rtc',
        desc: '',
        url: '',
        class: 'textval'
    }, {
        name: 'rp',
        desc: '',
        url: '',
        class: 'textval'
    }, {
        name: 'bdo',
        desc: '',
        url: '',
        class: 'textval'
    }, {
        name: 'dd',
        desc: '',
        url: '',
        class: 'blockval'
    }, {
        name: 'dl',
        desc: '',
        url: '',
        class: 'blockval'
    }, {
        name: 'dt',
        desc: '',
        url: '',
        class: 'blockval'
    }, {
        name: 'button',
        desc: '',
        url: '',
        class: 'formval'
    }, {
        name: 'datalist',
        desc: '',
        url: '',
        class: 'formval'
    }, {
        name: 'summary',
        desc: '',
        url: '',
        class: 'interactiveval'
    }, {
        name: 'header',
        desc: '',
        url: '',
        class: 'documentval'
    }, {
        name: 'h5',
        desc: '',
        url: '',
        class: 'documentval'
    }, {
        name: 'summary',
        desc: '',
        url: '',
        class: 'documentval'
    }, {
        name: 'th',
        desc: '',
        url: '',
        class: 'tableval'
    }],
    [{
        name: 'style',
        desc: '',
        url: '',
        class: 'metaval'
    }, {
        name: 'script',
        desc: '',
        url: '',
        class: 'metaval'
    }, {
        name: 'dfn',
        desc: '',
        url: '',
        class: 'textval'
    }, {
        name: 'u',
        desc: '',
        url: '',
        class: 'textval'
    }, {
        name: 'bdi',
        desc: '',
        url: '',
        class: 'textval'
    }, {
        name: 'ins',
        desc: '',
        url: '',
        class: 'textval'
    }, {
        name: 'del',
        desc: '',
        url: '',
        class: 'textval'
    }, {
        name: 'wbr',
        desc: '',
        url: '',
        class: 'textval'
    }, {
        name: 'blockquote',
        desc: '',
        url: '',
        class: 'blockval'
    }, {
        name: 'dialog',
        desc: '',
        url: '',
        class: 'blockval'
    }, {
        name: 'textarea',
        desc: '',
        url: '',
        class: 'formval'
    }, {
        name: 'keygen',
        desc: '',
        url: '',
        class: 'formval'
    }, {
        name: 'progress',
        desc: '',
        url: '',
        class: 'formval'
    }, {
        name: 'details',
        desc: '',
        url: '',
        class: 'interactiveval'
    }, {
        name: 'footer',
        desc: '',
        url: '',
        class: 'documentval'
    }, {
        name: 'h6',
        desc: '',
        url: '',
        class: 'documentval'
    }, {
        name: 'article',
        desc: '',
        url: '',
        class: 'documentval'
    }, {
        name: 'td',
        desc: '',
        url: '',
        class: 'tableval'
    }],
    [{
        name: '',
        desc: '',
        url: '',
        class: ''
    }, {
        name: '',
        desc: '',
        url: '',
        class: ''
    }, {
        name: '',
        desc: '',
        url: '',
        class: ''
    }, {
        name: '',
        desc: '',
        url: '',
        class: ''
    }, {
        name: '',
        desc: '',
        url: '',
        class: ''
    }, {
        name: '',
        desc: '',
        url: '',
        class: ''
    }, {
        name: '',
        desc: '',
        url: '',
        class: ''
    }, {
        name: '',
        desc: '',
        url: '',
        class: ''
    }, {
        name: '',
        desc: '',
        url: '',
        class: ''
    }, {
        name: '',
        desc: '',
        url: '',
        class: ''
    }, {
        name: '',
        desc: '',
        url: '',
        class: ''
    }, {
        name: '',
        desc: '',
        url: '',
        class: ''
    }, {
        name: '',
        desc: '',
        url: '',
        class: ''
    }, {
        name: '',
        desc: '',
        url: '',
        class: ''
    }, {
        name: '',
        desc: '',
        url: '',
        class: ''
    }, {
        name: '',
        desc: '',
        url: '',
        class: ''
    }, {
        name: '',
        desc: '',
        url: '',
        class: ''
    }, {
        name: '',
        desc: '',
        url: '',
        class: ''
    }],
    [{
        name: '',
        desc: '',
        url: '',
        class: ''
    }, {
        name: '',
        desc: '',
        url: '',
        class: ''
    }, {
        name: '',
        desc: '',
        url: '',
        class: ''
    }, {
        name: '',
        desc: '',
        url: '',
        class: ''
    }, {
        name: '',
        desc: '',
        url: '',
        class: ''
    }, {
        name: 'img',
        desc: '',
        url: '',
        class: 'embedval'
    }, {
        name: 'picture',
        desc: '',
        url: '',
        class: 'embedval'
    }, {
        name: 'iframe',
        desc: '',
        url: '',
        class: 'embedval'
    }, {
        name: 'embed',
        desc: '',
        url: '',
        class: 'embedval'
    }, {
        name: 'object',
        desc: '',
        url: '',
        class: 'embedval'
    }, {
        name: 'param',
        desc: '',
        url: '',
        class: 'embedval'
    }, {
        name: 'video',
        desc: '',
        url: '',
        class: 'embedval'
    }, {
        name: 'audio',
        desc: '',
        url: '',
        class: 'embedval'
    }, {
        name: 'source',
        desc: '',
        url: '',
        class: 'embedval'
    }, {
        name: 'canvas',
        desc: '',
        url: '',
        class: 'embedval'
    }, {
        name: 'map',
        desc: '',
        url: '',
        class: 'embedval'
    }, {
        name: 'area',
        desc: '',
        url: '',
        class: 'embedval'
    }, {
        name: 'track',
        desc: '',
        url: '',
        class: 'embedval'
    }],
    [{
        name: '',
        desc: '',
        url: '',
        class: ''
    }, {
        name: '',
        desc: '',
        url: '',
        class: ''
    }, {
        name: '',
        desc: '',
        url: '',
        class: ''
    }, {
        name: '',
        desc: '',
        url: '',
        class: ''
    }, {
        name: '',
        desc: '',
        url: '',
        class: ''
    }, {
        name: '',
        desc: '',
        url: '',
        class: ''
    }, {
        name: '',
        desc: '',
        url: '',
        class: ''
    }, {
        name: '',
        desc: '',
        url: '',
        class: ''
    }, {
        name: '',
        desc: '',
        url: '',
        class: ''
    }, {
        name: '',
        desc: '',
        url: '',
        class: ''
    }, {
        name: '',
        desc: '',
        url: '',
        class: ''
    }, {
        name: '',
        desc: '',
        url: '',
        class: ''
    }, {
        name: '',
        desc: '',
        url: '',
        class: ''
    }, {
        name: '',
        desc: '',
        url: '',
        class: ''
    }, {
        name: '',
        desc: '',
        url: '',
        class: ''
    }, {
        name: '',
        desc: '',
        url: '',
        class: ''
    }, {
        name: '',
        desc: '',
        url: '',
        class: ''
    }, {
        name: '',
        desc: '',
        url: '',
        class: ''
    }]
]